let goodThings = [
  { title: "Smile at someone.", id: 0 },
  { title: "Say something nice.", id: 1 },
  { title: "Listen to someone intently.", id: 2 },
  { title: "Write someone an enouraging note or text.", id: 3 },
  { title: "Give a gift.", id: 4 },
  { title: "Check in on someone who looks up to you.", id: 5 },
  { title: "Donate to a good cause.", id: 6 },
  { title: "Bring someone a glass of water.", id: 7 },
  { title: "Throw away some trash you find.", id: 8 },
  { title: "Forgive someone.", id: 9 },
  { title: "Thank someone.", id: 10 },
  { title: "Spend time with someone who’ll enjoy it.", id: 11 },
  { title: "Exercise.", id: 12 },
  { title: "Clean up a mess.", id: 13 },
  { title: "Travel using green transportation.", id: 14 },
  { title: "Treat yourself to something small.", id: 15 },
  { title: "Ask someone for forgiveness.", id: 16 },
  { title: "Help take care of a friend.", id: 17 },
  { title: "Share your favorite song with someone.", id: 18 },
  { title: "Spend some time contemplating and writing.", id: 19 },
  { title: "Video call someone you haven’t seen in a while.", id: 20 },
  { title: "Drink a glass of water.", id: 21 },
  { title: "Get some fresh air.", id: 22 },
  { title: "Try again at something you didn’t complete.", id: 23 },
  { title: "Give someone a hug.", id: 24 },
  { title: "Go for a walk.", id: 25 },
  { title: "Read for fun.", id: 26 },
  { title: "Do more than is asked of you.", id: 27 }
];

export default goodThings;
